source 'https://rubygems.org'

gem 'activerecord'
gem 'activesupport'
gem 'factory_bot'
gem 'faker'
gem 'pg'

group :development, :test do
  gem 'byebug'
  gem 'database_cleaner-active_record'
  gem 'rspec'
end
